### ISSUE TITLE
standard_init_linux.go:207: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by slevit** [milaq/kodi-headless#4] opened 2019-05-30 17:00 UTC
Installed docker on rpi3b successfully and able to run hello-world and ubuntu containers with no hiccups. [docker-info.txt](https://github.com/milaq/kodi-headless/files/3237713/docker-info.txt)

[docker-terminal-session.txt](https://github.com/milaq/kodi-headless/files/3237918/docker-terminal-session.txt)
Admittedly, I can't wrap my head fully around how to properly construct the "/path/to/sources.xml:/config/userdata/sources.xml" run command directive, or, if it's even necessary if I don't want to enable automatic library cleaning (your README doesn't seem very clear on the topic). Nevertheless, the "exec format error" occurs with or without it.

I'd very much appreciate it if you'd take the time to look into this anomaly and offer your expert advice. I'll do my best to provide whatever additional documentation you require. Thanks in advance.

**Comment by milaq** [comment] 2019-05-31 18:38
No, you don't need to link the sources.xml into the container if you don't need automatic library cleaning.

Exec format error is due to using the wrong arch.
Your Raspberry Pi is an ARM machine. The prebuilt docker image you pull from the Docker Hub is x86.
You need to either cross-compile the image or build it directly on your Raspberry.

Closing this issue but feel free to ask further questions here if you need assistance.
Cheers

**Closed as completed by milaq** 2019-05-31 18:38 UTC

**Comment by slevit** [comment] 2019-05-31 20:17
Thanks, but this should have been attached the first time around.
[dpkg.txt](https://github.com/milaq/kodi-headless/files/3242754/dpkg.txt)

**Comment by milaq** [comment] 2019-06-02 09:51
The issue is not the host Docker package but the Kodi binaries inside the image. The binaries itself were built for x86 and not armhf.

**Comment by slevit** [comment] 2019-06-02 13:24
Thanks for clarifying that. Thought I'd scoot around your cross-compile or build directly suggestion by pulling the lsioarmhf/kodi-headless image from Docker Hub instead. No "exec format error", but no luck getting the container to run either. Nothing appears in the container logs and I'm assuming the container would show in the "docker ps" list if it were running in the background. I'll be reporting that issue in the appropriate place unless you think I'll be wasting my time.

**Comment by milaq** [comment] 2019-06-02 14:20
I'd suspect the configuration procedure differs from that image here.

I'd consult the readme and run command pf the above mentioned project to find out what went wrong.

It's always a good idea to file an issue if there's an actual issue with the image and not a misconfiguration.

Good luck
